ControleEstacionamento/Models/ErrorViewModel.cs
namespace ControleEstacionamento.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleEstacionamento/Models/Tickets/TicketModel.cs
using ControleEstacionamento.Utils.Entidades;

namespace ControleEstacionamento.Models.Tickets
{
    public class TicketModel
    {
        public long ID { get; set; }
        public string Placa { get; set; }
        public DateTime? Hora_chegada { get; set; }
        public DateTime? Hora_saida { get; set; }
        public decimal Preco {  get; set; }
        public string Duracao
        {
            get
            {
                if (Hora_chegada.HasValue && Hora_saida.HasValue)
                {
                    TimeSpan duracao = Hora_saida.Value - Hora_chegada.Value;
                    return $"{(int)duracao.TotalHours}:{duracao.Minutes}:{duracao.Seconds}";
                }
            return "";
            }
        }
        public int TempoCobrado
        {
            get
            {
                if (Hora_chegada.HasValue && Hora_saida.HasValue)
                {
                    TimeSpan duracao = Hora_saida.Value - Hora_chegada.Value;
                    if (duracao.TotalMinutes <= 30)
                    {
                        return 1;
                    }
                    int horaCompleta = (int)(duracao.TotalMinutes / 60);
                    int tolerancia = (int)(duracao.TotalMinutes % 60);
                    if (tolerancia > 10)
                    {
                        horaCompleta += 1;
                    }
                    return horaCompleta;
                }
                return 0;
            }
        }

        public TicketModel()
        {
            
        }

        public TicketModel(Ticket ticket)
        {
            ID = ticket.ID;
            Placa = ticket.Placa;
            Hora_chegada = ticket.Hora_chegada;
            Hora_saida = ticket.Hora_saida;
            Preco = ticket.Preco;
        }

        public Ticket GetEntidade()
        {
            return new Ticket()
            {
                ID = ID,
                Placa = Placa,
                Hora_chegada = Hora_chegada,
                Hora_saida = Hora_saida,
                Preco = Preco
            };
        }

    }
}

ControleEstacionamento/Models/Tickets/TicketsModel.cs
namespace ControleEstacionamento.Models.Tickets
{
    public class TicketsModel
    {
        public List<TicketModel> Tickets { get; set;}
    }
}

ControleEstacionamento/Controllers/HomeController.cs
using System.Diagnostics;
using ControleEstacionamento.Models;
using ControleEstacionamento.Models.Tickets;
using ControleEstacionamento.Utils.Entidades;
using Microsoft.AspNetCore.Mvc;

namespace ControleEstacionamento.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var model = new TicketsModel();
            model.Tickets = new List<TicketModel>();
            var tickets = new Ticket().GetAll();

            model.Tickets = tickets.Select(ticketEntidade => new TicketModel(ticketEntidade)).ToList();

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

ControleEstacionamento/Controllers/PrecosController.cs
using Microsoft.AspNetCore.Mvc;

namespace ControleEstacionamento.Controllers
{
    public class PrecosController : Controller
    {
        public IActionResult Precos()
        {
            return View();
        }
    }
}

ControleEstacionamento/Controllers/TicketController.cs
using ControleEstacionamento.Models.Tickets;
using ControleEstacionamento.Utils.Entidades;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace ControleEstacionamento.Controllers
{
    public class TicketController : Controller
    {
        
        [HttpPost]
        public IActionResult MarcarEntrada(string placa)
        {
            new Ticket().MarcarEntrada(placa);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult MarcarSaida(string placa)
        {
            new Ticket().MarcarSaida(placa);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult FormularioEntrada()
        {
            return View();
        }

        [HttpGet]
        public IActionResult FormularioSaida()
        {
            return View();
        }

    }
}

ControleEstacionamento/Views/Home/Index.cshtml
@using ControleEstacionamento.Models.Tickets
@model TicketsModel
<h1 class="float-start mb-3 text-primary">Carro Bem Guardado</h1>
<div class="text-center">
    <div class="g-5 float-end mt-2">
        <a class="btn btn-outline-success" asp-controller="Ticket" asp-action="FormularioEntrada">Marcar Entrada</a>
        <a class="btn btn-outline-danger" asp-controller="Ticket" asp-action="FormularioSaida">Marcar Saída</a>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Placa</th>
                <th>Horário de chegada</th>
                <th>Horário de saída</th>
                <th>Duração</th>
                <th>Tempo Cobrado (hora)</th>
                <th>Preço</th>
                <th>Valor a pagar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Tickets)
            {
                <tr>
                    <td>@item.Placa</td>
                    <td>@item.Hora_chegada</td>
                    <td>@item.Hora_saida</td>
                    <td>@item.Duracao</td>
                    <td>@item.TempoCobrado</td>
                    <td>R$2,00</td>
                    <td>@item.Preco.ToString("C2")</td>
                </tr>
            }
        </tbody>
    </table>
</div>

ControleEstacionamento/Views/Precos/Precos.cshtml
<div class="text-center">
    <h1 class="text-primary">Tabela de Preços</h1>
    <h4>Preços válidos de 01/01/2025 à 31/01/2025</h4>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Tempo de Permanência</th>
            <th>Preço (R$)</th
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Até 30 minutos</td>
            <td>1,00</td>
        </tr>
        <tr>
            <td>Acima de 30 min até 1h:10</td>
            <td>2,00</td>
        </tr>
        <tr>
            <td>Acima de 1h:10 até 2h:10</td>
            <td>3,00</td>
        </tr>
        <tr>
            <td>Acima de 2h:10 até 3h:10</td>
            <td>4,00</td>
        </tr>
        <tr>
            <td>Acima de 3h:10 até 4h:10</td>
            <td>5,00</td>
        </tr>
        <tr>
            <td>Acima de 4h:10 até 5h:10</td>
            <td>6,00</td>
        </tr>
    </tbody>

</table>
</div>

ControleEstacionamento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControleEstacionamento</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleEstacionamento.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ControleEstacionamento</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Precos" asp-action="Precos">Tabela de Preços</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ControleEstacionamento - Conexão com Banco: @(ControleEstacionamento.Utils.Database.DBConnection.TestarConexao())
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ControleEstacionamento/Views/Ticket/FormularioEntrada.cshtml
<form method="post" asp-action="MarcarEntrada">
    <input class="form-control" type="text" name="placa" placeholder="Digite a placa do veículo" required />
    <button type="submit" class="btn btn-success mt-2">Marcar entrada</button>
</form>
<a asp-controller="Home" asp-action="Index" class="btn btn-secondary float-end">Voltar</a>

ControleEstacionamento/Views/Ticket/FormularioSaida.cshtml
<form method="post" asp-action="MarcarSaida">
    <input class="form-control" type="text" name="placa" placeholder="Digite a placa do veículo" required />
    <button type="submit" class="btn btn-danger mt-2">Marcar saída</button>
</form>
<a asp-controller="Home" asp-action="Index" class="btn btn-secondary float-end">Voltar</a>